import type { Property, Agent, Testimonial, BlogPost, Location } from "./types";

export const properties: Property[] = [
  {
    id: "1",
    title: "One Madison Residences",
    price: 8500,
    priceUnit: "month",
    area: 1869,
    bedrooms: 3,
    bathrooms: 2,
    rating: 4.9,
    reviewCount: 24,
    address: "1 Madison Avenue",
    city: "New York",
    type: "apartment",
    status: "for-rent",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    featured: true,
    yearBuilt: 2020,
    description: "White-glove full-service residences above Madison Square Park with triple-aspect floor plans, chef's kitchen, and in-unit laundry.",
    amenities: ["Doorman", "Concierge", "Rooftop Lounge", "Gym", "Bike Storage", "Package Room"],
  },
  {
    id: "2",
    title: "The Kensington Residences",
    price: 12500,
    priceUnit: "month",
    area: 2100,
    bedrooms: 3,
    bathrooms: 3,
    rating: 5.0,
    reviewCount: 47,
    address: "210 Central Park South",
    city: "New York",
    type: "apartment",
    status: "for-rent",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
    featured: true,
    yearBuilt: 2021,
    description: "Landmark tower apartments with direct Central Park views, bespoke Italian kitchens, and private residents' club on the 42nd floor.",
    amenities: ["Private Club Floor", "Valet Parking", "Spa", "Screening Room", "Concierge", "Wine Storage"],
  },
  {
    id: "3",
    title: "Southbank Sky Residences",
    price: 7200,
    priceUnit: "month",
    area: 1650,
    bedrooms: 2,
    bathrooms: 2,
    rating: 4.8,
    reviewCount: 18,
    address: "88 Southbank Boulevard",
    city: "Melbourne",
    type: "apartment",
    status: "for-rent",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
    featured: true,
    yearBuilt: 2019,
    description: "High-rise sky residences with floor-to-ceiling glazing overlooking the Yarra River, engineered oak floors, and premium integrated appliances.",
    amenities: ["Concierge", "Infinity Pool", "Residents' Lounge", "Gym", "EV Charging", "Storage Cage"],
  },
  {
    id: "4",
    title: "Grand Canal Apartments",
    price: 2850000,
    priceUnit: "",
    area: 2400,
    bedrooms: 3,
    bathrooms: 2,
    rating: 5.0,
    reviewCount: 33,
    address: "44 Collins Street",
    city: "Melbourne",
    type: "apartment",
    status: "for-sale",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    featured: true,
    yearBuilt: 2022,
    description: "Architecturally awarded whole-floor apartment with private lift access, 270-degree city panorama, and custom joinery throughout.",
    amenities: ["Private Lift", "Wraparound Terrace", "Smart Home", "Wine Cellar", "2 Car Parks", "Storage"],
  },
  {
    id: "5",
    title: "Peninsula Apartments",
    price: 380000,
    priceUnit: "",
    area: 1860,
    bedrooms: 6,
    bathrooms: 3,
    rating: 4.0,
    reviewCount: 29,
    address: "18 Broklyn Street",
    city: "New York",
    type: "villa",
    status: "for-sale",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
    featured: true,
    yearBuilt: 2021,
    description: "Waterfront villa with breathtaking views and private dock access.",
    amenities: ["Private Dock", "Pool", "Home Theater", "Gym"],
  },
  {
    id: "7",
    title: "Malibu Cliff Villa",
    price: 2850000,
    priceUnit: "",
    area: 3200,
    bedrooms: 5,
    bathrooms: 4,
    rating: 4.8,
    reviewCount: 31,
    address: "42 Ocean View Drive",
    city: "California",
    type: "villa",
    status: "for-sale",
    image: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&q=80",
    featured: false,
    yearBuilt: 2019,
    description: "Dramatic cliffside villa with floor-to-ceiling ocean views and a private infinity pool overlooking the Pacific.",
    amenities: ["Infinity Pool", "Private Gym", "Home Theater", "Wine Cellar", "3-Car Garage"],
  },
  {
    id: "8",
    title: "Desert Rose Estate",
    price: 1750000,
    priceUnit: "",
    area: 2800,
    bedrooms: 4,
    bathrooms: 3,
    rating: 4.7,
    reviewCount: 19,
    address: "18 Sunstone Lane",
    city: "Las Vegas",
    type: "villa",
    status: "for-sale",
    image: "https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=800&q=80",
    featured: false,
    yearBuilt: 2021,
    description: "Contemporary desert villa blending indoor-outdoor living with a resort-style backyard and mountain backdrop.",
    amenities: ["Pool & Spa", "Outdoor Kitchen", "Smart Home", "Solar Panels", "Guest Suite"],
  },
  {
    id: "9",
    title: "Lakefront Haven Villa",
    price: 3400000,
    priceUnit: "",
    area: 4100,
    bedrooms: 6,
    bathrooms: 5,
    rating: 5.0,
    reviewCount: 44,
    address: "7 Lakeshore Boulevard",
    city: "Melbourne",
    type: "villa",
    status: "for-sale",
    image: "https://images.unsplash.com/photo-1588854337115-1c67d9247e4d?w=800&q=80",
    featured: false,
    yearBuilt: 2022,
    description: "Architecturally striking lakefront villa with private pontoon, heated pool and panoramic water views from every room.",
    amenities: ["Private Pontoon", "Heated Pool", "Rooftop Terrace", "Butler Quarters", "Home Gym"],
  },
  {
    id: "10",
    title: "Midtown Commerce Tower",
    price: 4200000,
    priceUnit: "",
    area: 8500,
    bedrooms: 0,
    bathrooms: 6,
    rating: 4.8,
    reviewCount: 22,
    address: "310 Fifth Avenue",
    city: "New York",
    type: "commercial",
    status: "for-sale",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
    featured: false,
    yearBuilt: 2018,
    description: "Premium grade-A office tower in the heart of Midtown Manhattan with floor plates of up to 1,700 sq ft, 24/7 concierge, and direct subway access.",
    amenities: ["24/7 Concierge", "Conference Rooms", "Server Room", "Rooftop Terrace", "Underground Parking", "Fiber Internet"],
  },
  {
    id: "11",
    title: "Sunset Strip Retail Plaza",
    price: 2750000,
    priceUnit: "",
    area: 5200,
    bedrooms: 0,
    bathrooms: 4,
    rating: 4.6,
    reviewCount: 17,
    address: "8800 Sunset Boulevard",
    city: "California",
    type: "commercial",
    status: "for-sale",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
    featured: false,
    yearBuilt: 2020,
    description: "High-visibility retail and office plaza on one of LA's most trafficked corridors, featuring 12 ground-floor retail units and 3 upper-floor office suites.",
    amenities: ["High Foot Traffic", "Shared Lobby", "Loading Bay", "CCTV", "Ample Parking", "Signage Rights"],
  },
  {
    id: "12",
    title: "The Exchange Business Hub",
    price: 6800000,
    priceUnit: "",
    area: 12000,
    bedrooms: 0,
    bathrooms: 10,
    rating: 5.0,
    reviewCount: 38,
    address: "22 Collins Street",
    city: "Melbourne",
    type: "commercial",
    status: "for-sale",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800&q=80",
    featured: false,
    yearBuilt: 2023,
    description: "Melbourne's newest landmark commercial hub, offering open-plan floors with city views, co-working zones, and a ground-floor dining precinct.",
    amenities: ["Co-working Zones", "Boardrooms", "Bike Storage", "Shower Facilities", "Café Precinct", "EV Charging"],
  },
  {
    id: "13",
    title: "Fremont Innovation Campus",
    price: 5100000,
    priceUnit: "",
    area: 9800,
    bedrooms: 0,
    bathrooms: 8,
    rating: 4.9,
    reviewCount: 29,
    address: "45 Innovation Drive",
    city: "Las Vegas",
    type: "commercial",
    status: "for-sale",
    image: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=800&q=80",
    featured: false,
    yearBuilt: 2021,
    description: "Purpose-built technology and innovation campus with flexible open floor plans, dedicated server infrastructure, and collaborative break-out areas.",
    amenities: ["Dedicated Server Rooms", "Open Floor Plans", "Break-out Areas", "Helipad", "24/7 Security", "On-site Gym"],
  },
  {
    id: "14",
    title: "Ironworks Distribution Centre",
    price: 1850000,
    priceUnit: "",
    area: 18000,
    bedrooms: 0,
    bathrooms: 4,
    rating: 4.7,
    reviewCount: 14,
    address: "220 Industrial Parkway",
    city: "Las Vegas",
    type: "warehouse",
    status: "for-sale",
    image: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&q=80",
    featured: false,
    yearBuilt: 2017,
    description: "High-clearance distribution centre with 12m internal height, 6 dock-leveller bays, and direct freeway access — ideal for logistics and e-commerce operations.",
    amenities: ["6 Dock Levellers", "12m Clearance", "Freeway Access", "Sprinkler System", "Staff Amenities", "CCTV"],
  },
  {
    id: "15",
    title: "Steelyard Industrial Complex",
    price: 2300000,
    priceUnit: "",
    area: 24000,
    bedrooms: 0,
    bathrooms: 6,
    rating: 4.5,
    reviewCount: 9,
    address: "88 Forge Road",
    city: "Melbourne",
    type: "warehouse",
    status: "for-sale",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80",
    featured: false,
    yearBuilt: 2016,
    description: "Expansive multi-unit industrial complex with heavy-duty concrete flooring, three-phase power, and a secure yard of 4,000 sq ft for container storage.",
    amenities: ["Three-Phase Power", "Concrete Flooring", "Secure Yard", "Container Storage", "Office Fitout", "Roller Doors"],
  },
  {
    id: "16",
    title: "Apex Cold Storage Facility",
    price: 3100000,
    priceUnit: "",
    area: 15000,
    bedrooms: 0,
    bathrooms: 4,
    rating: 4.9,
    reviewCount: 21,
    address: "5 Refrigeration Way",
    city: "New York",
    type: "warehouse",
    status: "for-sale",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80",
    featured: false,
    yearBuilt: 2020,
    description: "State-of-the-art cold storage and food-grade warehouse with independently controlled temperature zones, solar power, and FDA-compliant fit-out.",
    amenities: ["Cold Storage Zones", "FDA Compliant", "Solar Power", "Generator Backup", "Loading Docks", "Office Block"],
  },
  {
    id: "17",
    title: "Pacific Rim Logistics Hub",
    price: 4600000,
    priceUnit: "",
    area: 32000,
    bedrooms: 0,
    bathrooms: 8,
    rating: 4.8,
    reviewCount: 33,
    address: "300 Harbor Industrial Drive",
    city: "California",
    type: "warehouse",
    status: "for-sale",
    image: "https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?w=800&q=80",
    featured: false,
    yearBuilt: 2022,
    description: "Premium port-adjacent logistics hub with cross-dock capability, automated conveyor infrastructure, and a 2,000 sq ft mezzanine office overlooking the floor.",
    amenities: ["Cross-Dock Capability", "Automated Conveyors", "Mezzanine Office", "Port Access", "EV Truck Charging", "24/7 Security"],
  },
  {
    id: "6",
    title: "Eaton Garth Penthouse",
    price: 1200000,
    priceUnit: "",
    area: 1860,
    bedrooms: 6,
    bathrooms: 3,
    rating: 5.0,
    reviewCount: 56,
    address: "18 Broklyn Street",
    city: "New York",
    type: "penthouse",
    status: "for-sale",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",
    featured: true,
    yearBuilt: 2023,
    description: "Exclusive penthouse with 360-degree city views, private terrace and helipad.",
    amenities: ["Helipad", "Private Pool", "Butler Service", "Cinema Room"],
  },
];

export const agents: Agent[] = [
  {
    id: "1",
    name: "Savannah Nguyen",
    title: "Senior Property Consultant",
    phone: "+1 (555) 234-5678",
    email: "savannah@topnotchproperties.com",
    image: "https://i.pravatar.cc/300?img=47",
    propertiesCount: 42,
    rating: 4.9,
  },
  {
    id: "2",
    name: "Annette Black",
    title: "Luxury Homes Specialist",
    phone: "+1 (555) 345-6789",
    email: "annette@topnotchproperties.com",
    image: "https://i.pravatar.cc/300?img=48",
    propertiesCount: 38,
    rating: 4.8,
  },
  {
    id: "3",
    name: "Kathryn Murphy",
    title: "Commercial Real Estate Expert",
    phone: "+1 (555) 456-7890",
    email: "kathryn@topnotchproperties.com",
    image: "https://i.pravatar.cc/300?img=49",
    propertiesCount: 55,
    rating: 5.0,
  },
  {
    id: "4",
    name: "David Hardson",
    title: "Investment Property Advisor",
    phone: "+1 (555) 567-8901",
    email: "david@topnotchproperties.com",
    image: "https://i.pravatar.cc/300?img=15",
    propertiesCount: 61,
    rating: 4.7,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Kristin Watson",
    role: "Web Designer",
    avatar: "https://i.pravatar.cc/100?img=44",
    content:
      "Top Notch Properties made finding our dream home effortless. The team was professional, knowledgeable, and genuinely cared about finding us the right property. We couldn't be happier with our new home.",
    rating: 5,
  },
  {
    id: "2",
    name: "Wade Warren",
    role: "President of Sales",
    avatar: "https://i.pravatar.cc/100?img=12",
    content:
      "Outstanding service from start to finish. The property recommendations were spot on and the process was completely transparent. I've already referred three colleagues who had equally great experiences.",
    rating: 5,
  },
  {
    id: "3",
    name: "Jessica Brown",
    role: "Founder & CEO",
    avatar: "https://i.pravatar.cc/100?img=45",
    content:
      "As a first-time buyer I was nervous, but the Top Notch Properties team guided me every step of the way. Their market knowledge is exceptional and the app made tracking listings incredibly easy.",
    rating: 5,
  },
  {
    id: "4",
    name: "David Anderson",
    role: "Customer",
    avatar: "https://i.pravatar.cc/100?img=13",
    content:
      "Sold my property 20% above asking price within two weeks. The marketing strategy and buyer network at Top Notch Properties is truly second to none. Highly recommend for any serious seller.",
    rating: 5,
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    title: "Top 8 Amazing Places to Stay in California",
    excerpt: "Discover the most exclusive and breathtaking luxury properties California has to offer, from Malibu beachfront estates to Napa Valley wine country retreats.",
    image: "https://images.unsplash.com/photo-1449034446853-66c86144b0ad?w=800&q=80",
    date: "November 4, 2024",
    author: "Savannah Nguyen",
    category: "Destinations",
    slug: "top-places-california",
  },
  {
    id: "2",
    title: "The Modern Buyer's Guide to Luxury Real Estate",
    excerpt: "Everything you need to know before purchasing a luxury property in today's market, from financing strategies to due diligence checklists.",
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80",
    date: "November 4, 2024",
    author: "Annette Black",
    category: "Buying Guide",
    slug: "luxury-buyers-guide",
  },
  {
    id: "3",
    title: "Top 5 Investment Destinations for 2025",
    excerpt: "Our market analysts identify the five real estate markets poised for exceptional growth, with exclusive data on rental yields and capital appreciation.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
    date: "November 4, 2024",
    author: "Kathryn Murphy",
    category: "Investment",
    slug: "investment-destinations-2025",
  },
  {
    id: "4",
    title: "Most Beautiful Waterfront Homes in the World",
    excerpt: "A curated collection of the world's most spectacular waterfront residences, showcasing extraordinary architecture and unparalleled natural settings.",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",
    date: "November 4, 2024",
    author: "David Hardson",
    category: "Lifestyle",
    slug: "beautiful-waterfront-homes",
  },
  {
    id: "5",
    title: "How to Stage Your Home for a Premium Sale",
    excerpt: "Professional staging advice from top interior designers that can increase your property value by up to 15% and reduce time on the market.",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
    date: "November 4, 2024",
    author: "Savannah Nguyen",
    category: "Selling Tips",
    slug: "home-staging-premium-sale",
  },
  {
    id: "6",
    title: "The Rise of Smart Homes in Luxury Real Estate",
    excerpt: "How AI and automation are transforming luxury living spaces, and why smart home technology is now a must-have for high-end buyers.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
    date: "November 4, 2024",
    author: "Annette Black",
    category: "Technology",
    slug: "smart-homes-luxury-real-estate",
  },
];

export const locations: Location[] = [
  {
    city: "California",
    country: "US",
    listingsCount: 7,
    image: "https://images.unsplash.com/photo-1449034446853-66c86144b0ad?w=600&q=80",
  },
  {
    city: "Las Vegas",
    country: "US",
    listingsCount: 3,
    image: "https://images.unsplash.com/photo-1605833556294-ea5c7a74f57d?w=600&q=80",
  },
  {
    city: "Melbourne",
    country: "AU",
    listingsCount: 13,
    image: "https://images.unsplash.com/photo-1545044846-351ba102b6d5?w=600&q=80",
  },
  {
    city: "New York",
    country: "US",
    listingsCount: 3,
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=600&q=80",
  },
];

export const stats = [
  { value: "20.5K", label: "Featured Projects" },
  { value: "100.5K", label: "Luxury Houses" },
  { value: "150.5K", label: "Satisfied Clients" },
  { value: "30K+", label: "Trusted Agents" },
];

export const propertyCategories = [
  { type: "apartment", label: "Apartment", count: 6, icon: "Building2" },
  { type: "villa", label: "Villa", count: 4, icon: "Home" },
  { type: "commercial", label: "Commercial", count: 6, icon: "Building" },
  { type: "warehouse", label: "Warehouse", count: 4, icon: "Warehouse" },
];
